import type { Metadata } from "next";
import { Geist_Mono, Work_Sans, Google_Sans_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SettingsProvider } from "@/components/settings-provider";
import { Header } from "@/components/layout/header";
import { TechFilterProvider } from "@/context/tech-filter";
import { Footer } from "@/components/layout/footer";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { SidebarToggle } from "@/components/layout/sidebar-toggle";
import { cookies } from "next/headers";
import type { Viewport } from "next";
import { MainWrapper } from "@/components/layout/main-wrapper";

const fontSans = Work_Sans({
  variable: "--sammce-font-sans",
  subsets: ["latin"],
});

const fontCode = Google_Sans_Code({
  variable: "--sammce-font-code",
  subsets: ["latin"],
});

const fontMono = Geist_Mono({
  variable: "--sammce-font-mono",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} ${fontCode.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SettingsProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              <TechFilterProvider>
                <AppSidebar />
                <Header />
                <MainWrapper>
                  <SidebarToggle />
                  {children}
                </MainWrapper>
                <Footer />
              </TechFilterProvider>
            </SidebarProvider>
          </SettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "cyan" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};
